version: "3"
services:
  sqs:
    image: s12v/elasticmq:latest
    ports:
      - "9324:9324"
    networks:
      - cloud

  dynamo:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    networks:
      - cloud

  serverless:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    depends_on:
      - sqs
      - dynamo
    networks:
      - cloud

networks:
  cloud: